//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Isaac_Cabria_Diez
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int EmpleadoId { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public System.DateTime Nacimiento { get; set; }
        public float SalarioAnual { get; set; }
        public string Telefono { get; set; }
        public bool Activo { get; set; }
        public int DepartamentoId { get; set; }
    
        public virtual Departamento Departamento { get; set; }
    }
}
